### ISSUE TITLE
Creación de Clases para Objetos en PHP

### ISSUE THREAD

**Issue by ltaverao95** [julianalbino258/viaticos#5]
Crear clases del lado del servidor con su respectiva carpeta, basarse en la estructura de carpetas en: Servidor/DTO/SolicitudViaje/SolicitudViajeDTO.php

Carpetas con archivos: 

1. Servidor/DTO/LegalizacionViatico/LegalizacionViaticoDTO.php
2. Servidor/DTO/AprobacionViaje/AprobacionViajeDTO.php

En cada archivo crear atributos basados en los archivos del cliente:

1. LegalizacionViaticoDTO.php basarse en LegalizacionViaticoModel.js
2. AprobacionViajeDTO.php basarse en AprobacionViajeModel.js

**NOTA:** 

- No crear los métodos, solo atributos.
- Cambiar los valores tipo fecha: new Date() por new DateTime()

**Comment by julianalbino258** [comment]
Se realiza el cambio de New Date a New DateTime  y no funciona. Se tuvo que poner null mientras tanto
